Add `useSetOff`
seamapi/react pull request #568
Opened 2023-11-08 22:58 UTC by xplato

2023-11-08 23:48 UTC, razor-x approved these changes

2023-11-08 23:50 UTC, razor-x requested changes
Actually, quick question to resolve before merge

2023-11-08 23:50 UTC, razor-x commented on src/lib/seam/thermostats/use-update-off.ts
> +      is_fan_running: false,
Are we sure this always results in the fan turning off?

<img width="325" alt="image" src="https://github.com/seamapi/react/assets/721372/f8b12832-4e34-4a60-8dc9-ec2fa04b5821">

2023-11-08 23:51 UTC, razor-x commented on src/lib/seam/thermostats/use-update-off.ts
Need to rename file.

2023-11-08 23:52 UTC, xplato commented on src/lib/seam/thermostats/use-update-off.ts
Ooh thank you

2023-11-09 00:17 UTC, razor-x approved these changes

2023-11-09 01:48 UTC, merged