feat: Add `disableDeviceDetails`
seamapi/react pull request #607
Opened 2024-03-15 17:41 UTC by xplato

2024-03-15 17:49 UTC, razor-x requested changes
Agree the name is confusing, it sounds like this will disable the `DeviceDetails` component somehow. I'm not sure this prop is is scope of this project. Similar to what happened with https://github.com/seamapi/react/pull/585

2024-03-15 17:57 UTC, xplato commented
@razor-x Good point. Any alternative ideas? `disableThermostatMetaDetails`? I don't like any of these 😅

2024-03-15 21:45 UTC, razor-x commented
Can we just recommend the CSS solution for this case for now?

Do you happen to know the use case or motivation for hiding just this section?

2024-04-27 02:57 UTC, razor-x commented
Closing in favor of https://github.com/seamapi/react/pull/623

2024-04-27 02:57 UTC, closed without merging