fix: use dynamic images as image size too large
seamapi/react pull request #619
Opened 2024-04-08 05:39 UTC by mikewuu

closes #616 

This is a POC

### Before

![CleanShot 2024-04-08 at 14 37 47@2x](https://github.com/seamapi/react/assets/11449462/8f4f4b5f-2223-4d45-b0fe-e48eb15c2bb4)

### After

![CleanShot 2024-04-08 at 14 38 04@2x](https://github.com/seamapi/react/assets/11449462/ce52766a-2a41-450e-ba4f-002bd5a98d1b)

2024-04-30 01:09 UTC, dawnho approved these changes

2024-04-30 01:19 UTC, razor-x requested changes
Note this is a test branch to verify the solution. The optimized URLs will be returned from the API with no update needed to this project. Blocking to avoid accidental merge. 

Currently, the images do not load with this change: https://react-ka4irjlds.seam.vc/examples/basic/

2024-05-01 16:11 UTC, razor-x commented on vercel.json
> +          "value": "default-src 'self'; connect-src 'self' https://connect.getseam.com; img-src 'self' https://connect.getseam.com https://console.seam.co; font-src 'self' https://fonts.gstatic.com;
This is going to be an issue. If we suddenly change image hosts we will break consumers using CSP.

2024-05-12 07:57 UTC, mikewuu commented
closing as handled via https://github.com/seamapi/seam-connect/pull/6866

2024-05-12 07:57 UTC, closed without merging